name: "provision-with-micromamba"
description: "provision a CI instance using micromamba"
branding:
  icon: "chevrons-right"
  color: "green"
inputs:
  environment-file:
    description: >-
      The environment.yml or .lock file for the conda environment. If 'false', no enviroment will be created.
    required: true
    default: environment.yml
  environment-name:
    description: >-
      The name of the conda environment (defaults to name from the environment.yml file).
      Required if 'environment-file' is a .lock file.
    required: false
  micromamba-version:
    description: >-
      Version of micromamba to use, eg. '0.20' (default 'latest').
    required: false
    default: "latest"
  extra-specs:
    description: >-
      Extra specifications to install (default empty)
    required: false
    default: ""
  cache-downloads:
    description: >-
      If 'true', cache downloaded packages across calls to the provision-with-micromamba action.
      Cache invalidation can be controlled using the 'cache-downloads-key' option.
    default: false
  cache-downloads-key:
    description: >-
      Optional custom download cache key used with 'cache-downloads: true'.
      The default download cache key will invalidate the cache once per day.
    required: false
  cache-env:
    description: >-
      If 'true', cache installed environments across calls to the provision-with-micromamba action.
      Cache invalidation can be controlled using the 'cache-env-key' option.
    default: false
  cache-env-key:
    description: >-
      Optional custom environment cache key used with 'cache-env: true'.
      The default environment cache key will invalidate the cache whenever the contents of the
      'environment-file' or 'extra-specs' change, plus once per day.
    required: false
  cache-env-always-update:
    description: >-
      If 'true', run 'micromamba update' even if the environment was restored from cache
      to make sure your environment is always up-to-date.
      This doesn't work currently.
    default: false

runs:
  using: "node16"
  main: "dist/main/index.js"
  post: "dist/post/index.js"
  post-if: success()
