name: Test caching

on:
  push:
    branches:
      - main
  pull_request: null

defaults:
  run:
    shell: bash -l {0}

jobs:
  test_download1:
    name: Test download cache 1/2
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: install mamba
        uses: ./
        with:
          cache-downloads: true

      - name: test environment name
        run: |
          python -c "import os; env = os.path.basename(os.environ['CONDA_PREFIX']); assert env == 'testenv'"

  test_download2:
    name: Test download cache 2/2
    needs: [test_download1]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: install mamba
        uses: ./
        with:
          cache-downloads: true

      - name: test environment name
        run: |
          python -c "import os; env = os.path.basename(os.environ['CONDA_PREFIX']); assert env == 'testenv'"

  test_env1:
    name: Test env cache 1/3
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: install mamba
        uses: ./
        with:
          cache-env: true

      - name: test environment name
        run: |
          python -c "import os; env = os.path.basename(os.environ['CONDA_PREFIX']); assert env == 'testenv'"

  test_env2:
    name: Test env cache 2/3
    needs: [test_env1]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: install mamba
        uses: ./
        with:
          cache-env: true

      - name: test environment name
        run: |
          python -c "import os; env = os.path.basename(os.environ['CONDA_PREFIX']); assert env == 'testenv'"

  test_env3:
    if: false # Doesn't work
    name: Test env cache 3/3
    needs: [test_env1]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: install mamba
        uses: ./
        with:
          cache-env: true
          cache-env-always-update: true

      - name: test environment name
        run: |
          python -c "import os; env = os.path.basename(os.environ['CONDA_PREFIX']); assert env == 'testenv'"
